apiVersion: v1
kind: Pod
metadata:
  labels:
    type: build-agent
spec:
  #securityContext:
  #  runAsUser: 1000
  containers:
  - name: hello-k8
    image: paulbouwer/hello-kubernetes:1.8
  restartPolicy: Never
